### ISSUE TITLE
connection refused after model is downloaded successfuly

### ISSUE THREAD

**Issue by palashkulsh** [g1ibby/llm-deploy#4]
Sorry to bother you again, but I've tried downloading models 2 times (separate ones, but this is failing everytime.) any pointers /direction in which i can check

![image](https://github.com/g1ibby/llm-deploy/assets/5735087/3315b946-a763-48e8-a0d5-b00269ac461b)

Download completed successfully.
Traceback (most recent call last):

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)

ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()

  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)

  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)

  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7782d5d7eb10>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4000): Max retries exceeded with url: /model/new (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7782d5d7eb10>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/llm_deploy/cli.py", line 135, in main
    app()

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/llm_deploy/cli.py", line 112, in model_deploy
    appl.model.pull(model_name, machine_id)

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/llm_deploy/model_manager.py", line 32, in pull
    self.litellm.add_model(model_name, ollama_addr)

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/llm_deploy/litellm.py", line 11, in add_model
    response = requests.post(f"{self.api_url}/model/new", json={
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/myenv/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=4000): Max retries exceeded with url: /model/new (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7782d5d7eb10>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by palashkulsh** [comment]
the ollama service was running fine on the instance even after this error though.

**Comment by g1ibby** [comment]
@palashkulsh I have fixed the error and pushed a fix to the repository. Please pull the latest version to resolve the issue.

In the updated version, the default behavior is to work with LiteLLM. However, if LiteLLM is not installed on your local machine, the code will now skip that part gracefully without causing any errors.

Please let me know if you have any further questions or if you encounter any issues after updating to the latest version and thank you to waiting!

**Comment by palashkulsh** [comment]
thank you so much @g1ibby !! the work provided by this repo is amazing.
gonna try llama 3 with this!!
